title: Arrow Acrobatics
description: >- # this means to ignore newlines until next key/value
   🚧 Under Construction 🚧<br><br>
   Theatrical circus performer specializing in 
   Aerial Rope and Aerial Straps

# Note:
# Not setting baseurl results in  both localhost:4000/ 
# and arrowacrobatics.github.io/portfolio-website working.
# (Eventhough they advise to set it?)

url: "" # the base hostname & protocol for your site, e.g. http://example.com

#####################
# Identity settings #
#####################

email: arrowacrobatics@gmail.com
github_username:  ArrowAcrobatics
instagram_username: ArrowAcrobatics

##################
# Build settings #
##################

markdown: kramdown

# See the theme repo: https://github.com/StartBootstrap/startbootstrap-clean-blog-jekyll
remote_theme: StartBootstrap/startbootstrap-clean-blog-jekyll

paginate:           5
paginate_path: "/posts/page:num/"

plugins:
  - jekyll-feed
  - jekyll-paginate


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
